CLIENT/Models/Customer.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CLIENT.Models
{
    public class Customer
    {
        public int CustomerId { get; set; }
        [Required(ErrorMessage = "First Name required")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Last Name required")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Address required")]
        public string Address { get; set; }
        public virtual List<Invoice> Invoices { get; set; }
    }
}

CLIENT/Models/ErrorViewModel.cs
using System;

namespace CLIENT.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CLIENT/Models/Invoice.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CLIENT.Models
{
    public class Invoice
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Date required")]
        public DateTime Date { get; set; }
        [Required(ErrorMessage = "Full Name required")]
        public int CustomerId { get; set; }
        [ForeignKey("CustomerId")]
        public virtual Customer Customer { get; set; }
    }
}

CLIENT/Controllers/CustomerController.cs
using CLIENT.IRepository;
using CLIENT.Models;
using CLIENT.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CLIENT.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerRepository _customerRepository;
        public Customer Customer { get; set; }
        public CustomerController(ICustomerRepository customerRepository)
        {
            _customerRepository = customerRepository;
        }

        public async Task<IActionResult> Index()
        {
            List<Customer> customers = await _customerRepository.GetAllData();

            return View(new MasterDataVM { Customers = customers });
        }


        [HttpPost]
        public async Task<IActionResult> Index(Customer customer)
        {
            var response = await _customerRepository.AddCustomer(customer);
            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                TempData["MessageInput"] = "Success Added Data.";
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Update(int id)
        {
            var response = await _customerRepository.GetCustomerById(id);
            List<Customer> customers = await _customerRepository.GetAllData();
            return View(new MasterDataVM { Customers = customers, Customer = response });
        }

        [HttpPost]
        public async Task<IActionResult> Update(Customer customer)
        {
            var response = await _customerRepository.UpdateCustomer(customer);
            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                TempData["MessageUpdate"] = "Success Updated Data.";
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _customerRepository.DeleteCustomer(id);

            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                TempData["MessageDelete"] = "Sukses Deleted Data.";
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

CLIENT/Controllers/HomeController.cs
using CLIENT.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CLIENT.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CLIENT/Controllers/InvoiceController.cs
using CLIENT.IRepository;
using CLIENT.Models;
using CLIENT.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace CLIENT.Controllers
{
    public class InvoiceController : Controller
    {
        private readonly IInvoiceRepository _invoiceRepository;
        public InvoiceController(IInvoiceRepository invoiceRepository)
        {
            _invoiceRepository = invoiceRepository;
        }

        public async Task<IActionResult> Index()
        {
            List<Invoice> invoices = await _invoiceRepository.GetAllData();
            List<CustomerVM> customers = await _invoiceRepository.GetCustomer();

            return View(new MasterDataVM { Invoices = invoices, CustomerVMs = customers });
        }

        [HttpPost]
        public async Task<IActionResult> Index(Invoice invoice)
        {
            var response = await _invoiceRepository.AddInvoice(invoice);
            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                TempData["MessageInput"] = "Success Added Data.";
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Update(int id)
        {
            var response = await _invoiceRepository.GetInvoiceById(id);
            List<Invoice> invoices = await _invoiceRepository.GetAllData();

            return View(new MasterDataVM { Invoices = invoices, Invoice = response});
        }

        [HttpPost]
        public async Task<IActionResult> Update(Invoice invoice)
        {
            var response = await _invoiceRepository.UpdateInvoice(invoice);
            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                TempData["MessageUpdate"] = "Success Updated Data.";
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Delete(int id)
        {
            var response = await _invoiceRepository.DeleteInvoice(id);

            if (response.StatusCode == System.Net.HttpStatusCode.OK)
            {
                TempData["MessageDelete"] = "Sukses Deleted Data.";
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

CLIENT/Views/Customer/Update.cshtml
@using CLIENT.ViewModel;

@model MasterDataVM
<!-- Page-Title -->
@{
    ViewData["Title"] = "Update Customer";
}

<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="btn-group pull-right">
                <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Customers</a></li>
                    <li class="breadcrumb-item active">Update Customer</li>
                </ol>
            </div>
            <h4 class="page-title">Update Customer</h4>
        </div>
    </div>
</div>
<!-- end page title end breadcrumb -->


<div class="row">
    <div class="col-12">
        <div class="card m-b-20">
            <div class="card-body">
                <form method="post">
                    <div class="form-group row" hidden>
                        <label for="example-month-input" asp-for="Customer.CustomerId" class="col-sm-2 col-form-label">Customer ID</label>
                        <div class="col-sm-3">
                            <input class="form-control" asp-for="Customer.CustomerId" readonly>
                            <span asp-validation-for="Customer.CustomerId" class="text-danger"></span>
                        </div>

                    </div>
                    <div class="form-group row">
                        <label asp-for="Customer.FirstName" class="col-sm-2 col-form-label">First Name<span class="req-star">*</span></label>
                        <div class="col-sm-3">
                            <input class="form-control" asp-for="Customer.FirstName" id="example-text-input">
                            <span asp-validation-for="Customer.FirstName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Customer.LastName" class="col-sm-2 col-form-label">Last Name<span class="req-star">*</span></label>
                        <div class="col-sm-3">
                            <input class="form-control" asp-for="Customer.LastName" id="example-text-input">
                            <span asp-validation-for="Customer.LastName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Customer.Address" class="col-sm-2 col-form-label">Address<span class="req-star">*</span></label>
                        <div class="col-sm-3">
                            <input class="form-control" asp-for="Customer.Address" id="example-text-input">
                            <span asp-validation-for="Customer.Address" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <button style="margin-right:.5em" type="submit" class="btn btn-primary waves-effect waves-light">Update</button>
                        <a class="btn btn-danger waves-effect waves-light" asp-controller="Customer" asp-action="Index">Back</a>
                    </div>
                </form>
            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

@section scripts{
    <partial name="_ValidationScriptsPartial" />
}

CLIENT/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CLIENT/Views/Invoice/Index.cshtml
@using CLIENT.ViewModel;

@model MasterDataVM
<!-- Page-Title -->
@{
    ViewData["Title"] = "Invoices";
}

<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="btn-group pull-right">
                <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Manage Data</a></li>
                    <li class="breadcrumb-item active">Invoices</li>
                </ol>
            </div>
            <h4 class="page-title">Invoices</h4>
            <br />
            <div class="breadcrumbs flat">
                <a style="text-align: center;" asp-controller="Customer" asp-action="Index">Customers</a>
                <a style="text-align: center;" class="active">Invoices</a>
            </div>
        </div>
    </div>
</div>


<div class="row">
    <div class="col-12">
        <div class="card m-b-20">

            <div class="col-md-4 m-t-30">
                <div class="text-left">
                    <!-- Small modal -->
                    <button type="button" class="btn btn-primary waves-effect waves-light" data-toggle="modal" data-target=".bs-example-modal-lg">Add Invoice</button>
                </div>

                <div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title mt-0" id="myLargeModalLabel">Add Invoice</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            </div>
                            <div class="modal-body">
                                <form method="post">
                                    <div class="form-group row">
                                        <label for="example-month-input" asp-for="Invoice.CustomerId" class="col-sm-2 col-form-label">Customer Name<span class="req-star">*</span></label>
                                        <div class="col-sm-7">
                                            <select class="form-control" asp-for="Invoice.CustomerId">
                                                <option disabled selected value="">Customer Name</option>
                                                @foreach (var item in Model.CustomerVMs)
                                                {
                                                    <option value="@item.CustomerID">@item.FullName</option>
                                                }
                                            </select>
                                            <span asp-validation-for="Invoice.CustomerId" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="form-group row">
                                        <label for="example-month-input" asp-for="Invoice.Date" class="col-sm-2 col-form-label">Date<span class="req-star">*</span></label>
                                        <div class="col-sm-7">
                                            <input type="text" id="date" asp-for="Invoice.Date" class="form-control" placeholder="mm/dd/yyyy">
                                            <span asp-validation-for="Invoice.Date" class="text-danger"></span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <div>
                                            <button type="submit" class="btn btn-success waves-effect waves-light">
                                                Save
                                            </button>
                                            <button type="reset" class="btn btn-secondary waves-effect m-l-5" data-dismiss="modal">
                                                Back
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                        @*/.modal-content*@
                    </div> @*/.modal-dialog*@
                </div> @*/.modal*@
            </div>


            <div class="card-body">

                @if (TempData["MessageInput"] != null)
                {
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        @TempData["MessageInput"]
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }
                else if (TempData["MessageUpdate"] != null)
                {
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        @TempData["MessageUpdate"]
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }
                else if (TempData["MessageDelete"] != null)
                {
                    <div class="alert alert-success alert-dismissible fade show" role="alert">
                        @TempData["MessageDelete"]
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }
                else if (TempData["MessageFailed"] != null)
                {
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        @TempData["MessageFailed"]
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                }

                <h4 class="mt-0 header-title">List Invoices</h4>
                <table id="datatable" class="table table-bordered dt-responsive nowrap" cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Invoice ID</th>
                            <th>Date</th>
                            <th>Customer ID</th>
                            <th>Customer Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Model.Invoices.Count(); i++)
                        {

                            <tr>
                                <td>@(i + 1).</td>
                                <td>@Model.Invoices[i].Id</td>
                                <td>@Convert.ToDateTime(@Model.Invoices[i].Date).ToString("dd/MM/yyyy")</td>
                                <td>@Model.Invoices[i].CustomerId</td>
                                <td>@Model.Invoices[i].Customer.FirstName @Model.Invoices[i].Customer.LastName</td>
                                <td>
                                    <div id="modalRole-@i" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title mt-0" id="myModalLabel">Delete Invoice</h4>
                                                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                                                </div>
                                                <div class="modal-body">
                                                    <h5>Invoice ID: @Model.Invoices[i].Id</h5>
                                                    <h5>Date: @Convert.ToDateTime(@Model.Invoices[i].Date).ToString("dd/MM/yyyy")</h5>
                                                    <h5>Customer ID: @Model.Invoices[i].CustomerId</h5>
                                                    <h5>Customer Name: @Model.Invoices[i].Customer.FirstName @Model.Invoices[i].Customer.LastName</h5>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="button" class="btn btn-secondary waves-effect" data-dismiss="modal">Back</button>
                                                    <a type="button" class="btn btn-danger waves-effect waves-light" asp-controller="Invoice" asp-action="Delete" asp-route-id=" @Model.Invoices[i].Id">Delete</a>
                                                </div>
                                            </div>
                                            @*/.modal-content*@
                                        </div> @*/.modal-dialog*@
                                    </div> @*/.modal*@
                                    <a asp-controller="Invoice" asp-action="Update" asp-route-id=" @Model.Invoices[i].Id" type="button" class="btn btn-primary waves-effect waves-light">Update</a>
                                    <a href="#" class="btn btn-danger waves-effect waves-light" data-toggle="modal" data-target="#modalRole-@i">Delete</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->


@section scripts{
    <partial name="_ValidationScriptsPartial" />

    <script type="text/javascript">
        $(document).ready(function () {

            $('#date').datepicker({
                autoclose: true,
                format: "mm/dd/yyyy"
            });

        });
    </script>
}

CLIENT/Views/Invoice/Update.cshtml
@using CLIENT.ViewModel;

@model MasterDataVM
<!-- Page-Title -->
@{
    ViewData["Title"] = "Update Invoice";
}

<div class="row">
    <div class="col-sm-12">
        <div class="page-title-box">
            <div class="btn-group pull-right">
                <ol class="breadcrumb hide-phone p-0 m-0">
                    <li class="breadcrumb-item"><a href="#">Invoices</a></li>
                    <li class="breadcrumb-item active">Update Invoice</li>
                </ol>
            </div>
            <h4 class="page-title">Update Invoice</h4>
        </div>
    </div>
</div>
<!-- end page title end breadcrumb -->


<div class="row">
    <div class="col-12">
        <div class="card m-b-20">
            <div class="card-body">
                <form method="post">
                    <div class="form-group row">
                        <label for="example-month-input" asp-for="Invoice.Id" class="col-sm-2 col-form-label">Invoice ID</label>
                        <div class="col-sm-3">
                            <input class="form-control" asp-for="Invoice.Id" readonly>
                            <span asp-validation-for="Invoice.Id" class="text-danger"></span>
                        </div>

                    </div>
                    <div class="form-group row">
                        <label asp-for="Invoice.CustomerId" class="col-sm-2 col-form-label">Customer Name<span class="req-star">*</span></label>
                        <div class="col-sm-3">
                            <select disabled="disabled" class="form-control" asp-for="Invoice.CustomerId">
                                <option value="@Model.Invoice.CustomerId" selected="selected">@Model.Invoice.Customer.FirstName @Model.Invoice.Customer.LastName</option>
                            </select>
                            <input type="hidden" asp-for="Invoice.CustomerId" value="@Model.Invoice.CustomerId" />
                            <span asp-validation-for="Invoice.Id" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="Customer.LastName" class="col-sm-2 col-form-label">Date<span class="req-star">*</span></label>
                        <div class="col-sm-3">
                            <input type="text" id="date" asp-for="Invoice.Date" class="form-control" value="@Convert.ToDateTime(@Model.Invoice.Date).ToString("MM/dd/yyyy")">
                            <span asp-validation-for="Invoice.Date" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <button style="margin-right:.5em" type="submit" class="btn btn-primary waves-effect waves-light">Update</button>
                        <a class="btn btn-danger waves-effect waves-light" asp-controller="Invoice" asp-action="Index">Back</a>
                    </div>
                </form>
            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

@section scripts{
    <partial name="_ValidationScriptsPartial" />

    <script type="text/javascript">
        $(document).ready(function () {

            $('#date').datepicker({
                autoclose: true,
                format: "mm/dd/yyyy"
            });

        });
    </script>
}